# Replicate Table 2 Explainability paper Results `2025-07-13`

In [53]:
import pandas as pd

# 1. LLama33 70B

## 1.1. llama 33 70B FL:

In [241]:
df_llama33_70B_fl_exp = pd.read_pickle('july_result/llama33_70B_FL_318_metrics.pkl')
df_llama33_70B_fl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'iteration_results', 'respond_llm',
       'respond_time_llm', 'evaluation_time_llm',
       'total_evaluation_time_per_row', 'prompts_per_iteration',
       'pmid_contexts_per_iteration', 'pmid_changes_per_iteration',
       'termination_reason', 'iterations_completed',
       'llama33_70B_final_explanation', 'pmid_text', 'llama33_70B_ji_fl',
       'llama33_70B_fl_similarity_score_medcpt_dot',
       'llama33_70B_fl_similarity_score_scincl_dot', 'llama33_70B_fl_score',
       'feedback', 'evaluate_llm_response', 'all_predicates', 'bad_predicates',
       'good_predicates', 'agatha_score', 'num_predicates',
       'number_bad_predicates'],
      dtype='object')

In [286]:
cols = [
    'llama33_70B_ji_fl',
    'llama33_70B_fl_similarity_score_medcpt_dot',
    'llama33_70B_fl_similarity_score_scincl_dot',
    'llama33_70B_fl_score'
]

grouped_df = df_llama33_70B_fl_exp.groupby('index').agg('mean', numeric_only=True)

overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_llama33_70B_fl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['Feedback Loop (FL) llama33_70B '],
    'Jaccard':      [f"{overall_means['llama33_70B_ji_fl']:.2f}±{overall_stds['llama33_70B_ji_fl']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['llama33_70B_fl_similarity_score_medcpt_dot']:.2f}±{overall_stds['llama33_70B_fl_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['llama33_70B_fl_similarity_score_scincl_dot']:.2f}±{overall_stds['llama33_70B_fl_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['llama33_70B_fl_score']:.2f}±{overall_stds['llama33_70B_fl_score']:.2f}"]
})

summary

            Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  Feedback Loop (FL)  0.08±0.03   61.82±3.28  495.28±26.54   2.36±1.05

## 1.2. llama 33 70B BL:

In [192]:
df_llama33_70B_bl_exp = pd.read_pickle('july_result/llama33_70B_BL_318_metrics.pkl')
df_llama33_70B_bl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'llama33_70B_bl_response', 'bl_prompt_context',
       'pmid_text', 'llama33_70B_ji_bl',
       'llama33_70B_bl_bl_similarity_score_medcpt_dot',
       'llama33_70B_bl_similarity_score_scincl_dot', 'llama33_70B_score_bl',
       'feedback'],
      dtype='object')

In [285]:
cols = [
    'llama33_70B_ji_bl',
    'llama33_70B_bl_bl_similarity_score_medcpt_dot',
    'llama33_70B_bl_similarity_score_scincl_dot',
    'llama33_70B_score_bl'
]

grouped_df = df_llama33_70B_bl_exp.groupby('index').agg('mean', numeric_only=True)

overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_llama33_70B_bl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['BL llama33_70B'],
    'Jaccard':      [f"{overall_means['llama33_70B_ji_bl']:.2f}±{overall_stds['llama33_70B_ji_bl']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['llama33_70B_bl_bl_similarity_score_medcpt_dot']:.2f}±{overall_stds['llama33_70B_bl_bl_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['llama33_70B_bl_similarity_score_scincl_dot']:.2f}±{overall_stds['llama33_70B_bl_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['llama33_70B_score_bl']:.2f}±{overall_stds['llama33_70B_score_bl']:.2f}"]
})

summary

  Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0        BL  0.08±0.03   61.86±3.29  495.75±27.16   2.15±1.01

## 1.3. llama 33 70B RAW:

In [58]:
df_llama33_70B_raw_exp = pd.read_pickle('july_result/llma33_70B_RAW_318_metrics.pkl')
df_llama33_70B_raw_exp.columns

Index(['subj_name', 'obj_name', 'index', 'Raw_llama_33_70B_response',
       'ji_raw_llama33_70B', 'explanation_embedding',
       'similarity_score_medcpt_cosine_raw_llama33_70B',
       'similarity_score_medcpt_dot_raw_llama33_70B',
       'similarity_score_scincl_cosine_raw_llama33_70B',
       'similarity_score_scincl_dot_raw_llama33_70B', 'score_raw_llama33_70B',
       'feedback_raw_llama33_70B'],
      dtype='object')

In [284]:
cols = [
    'ji_raw_llama33_70B',
    'similarity_score_medcpt_dot_raw_llama33_70B',
    'similarity_score_scincl_dot_raw_llama33_70B',
    'score_raw_llama33_70B'
]

grouped_df = df_llama33_70B_raw_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T
summary_df

grp = df_llama33_70B_raw_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['RAW llama33_70B'],
    'Jaccard':      [f"{overall_means['ji_raw_llama33_70B']:.2f}±{overall_stds['ji_raw_llama33_70B']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['similarity_score_medcpt_dot_raw_llama33_70B']:.2f}±{overall_stds['similarity_score_medcpt_dot_raw_llama33_70B']:.2f}"],
    'Scincl (cos)': [f"{overall_means['similarity_score_scincl_dot_raw_llama33_70B']:.2f}±{overall_stds['similarity_score_scincl_dot_raw_llama33_70B']:.2f}"],
    'Correctness':  [f"{overall_means['score_raw_llama33_70B']:.2f}±{overall_stds['score_raw_llama33_70B']:.2f}"]
})

summary

  Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0       RAW  0.07±0.03   60.71±2.84  490.79±28.03   2.53±0.84

# 2. llama 31 8B

## 2.1. llama 31 8B FL:

In [235]:
df_llama31_8B_fl_exp = pd.read_pickle('july_result/llama31_8B_FL_318_metrics.pkl')
df_llama31_8B_fl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'iteration_results', 'respond_llm',
       'respond_time_llm', 'evaluation_time_llm',
       'total_evaluation_time_per_row', 'prompts_per_iteration',
       'pmid_contexts_per_iteration', 'pmid_changes_per_iteration',
       'termination_reason', 'iterations_completed', 'final_explanation',
       'pmid_text', 'llama31_8B_ji_fl',
       'llama31_8B_fl_similarity_score_medcpt_dot',
       'llama31_8B_fl_similarity_score_scincl_dot', 'llama31_8B_score_fl',
       'feedback_bseline'],
      dtype='object')

In [270]:
cols = [
    'llama31_8B_ji_fl',
    'llama31_8B_fl_similarity_score_medcpt_dot',
    'llama31_8B_fl_similarity_score_scincl_dot',
    'llama31_8B_score_fl'
]

grouped_df = df_llama31_8B_fl_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_llama31_8B_fl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['Feedback Loop (FL) llama31_8B'],
    'Jaccard':      [f"{overall_means['llama31_8B_ji_fl']:.2f}±{overall_stds['llama31_8B_ji_fl']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['llama31_8B_fl_similarity_score_medcpt_dot']:.2f}±{overall_stds['llama31_8B_fl_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['llama31_8B_fl_similarity_score_scincl_dot']:.2f}±{overall_stds['llama31_8B_fl_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['llama31_8B_score_fl']:.2f}±{overall_stds['llama31_8B_score_fl']:.2f}"]
})

summary

  Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0       RAW  0.07±0.03   61.17±3.24  491.25±26.50   1.75±0.86

## 2.2. llama 31 8B BL:

In [225]:
df_llama31_8B_bl_exp = pd.read_pickle('july_result/lama31_8B_BL_318_metrics.pkl')
df_llama31_8B_bl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'iteration_results', 'respond_llm',
       'respond_time_llm', 'evaluation_time_llm',
       'total_evaluation_time_per_row', 'prompts_per_iteration',
       'pmid_contexts_per_iteration', 'pmid_changes_per_iteration',
       'termination_reason', 'iterations_completed', 'final_explanation',
       'baseline_expl_llama31_8B', 'pmid_text', 'llama31_8B_ji_bl',
       'llama31_8B_bl_similarity_score_medcpt_dot',
       'llama31_8B_bl_similarity_score_scincl_dot', 'llama31_8B_score_bseline',
       'feedback_bseline'],
      dtype='object')

In [273]:
cols = [
    'llama31_8B_ji_bl',
    'llama31_8B_bl_similarity_score_medcpt_dot',
    'llama31_8B_bl_similarity_score_scincl_dot',
    'llama31_8B_score_bseline'
]

grouped_df = df_llama31_8B_bl_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_llama31_8B_bl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['BL llama31_8B'],
    'Jaccard':      [f"{overall_means['llama31_8B_ji_bl']:.2f}±{overall_stds['llama31_8B_ji_bl']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['llama31_8B_bl_similarity_score_medcpt_dot']:.2f}±{overall_stds['llama31_8B_bl_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['llama31_8B_bl_similarity_score_scincl_dot']:.2f}±{overall_stds['llama31_8B_bl_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['llama31_8B_score_bseline']:.2f}±{overall_stds['llama31_8B_score_bseline']:.2f}"]
})

summary

       Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  BL llama31_8B  0.07±0.03   61.51±3.25  494.37±26.09   1.84±0.90

## 2.3. llama 31 8B RAW:

In [63]:
df_llama31_8B_raw_exp = pd.read_pickle('july_result/llma31_8B_RAW_318_metrics.pkl')
df_llama31_8B_raw_exp.columns

Index(['subj_name', 'obj_name', 'index', 'Raw_llama_31_8B_response',
       'ji_raw_llama31_8B', 'similarity_score_medcpt_cosine_raw_llama31_8B',
       'similarity_score_medcpt_dot_raw_llama31_8B',
       'similarity_score_scincl_cosine_raw_llama31_8B',
       'similarity_score_scincl_dot_raw_llama31_8B', 'score_raw_llama31_8B',
       'feedback_raw_llama31_8B'],
      dtype='object')

In [272]:
cols = [
    'ji_raw_llama31_8B',
    'similarity_score_medcpt_dot_raw_llama31_8B',
    'similarity_score_scincl_cosine_raw_llama31_8B',
    'score_raw_llama31_8B'
]

grouped_df = df_llama31_8B_raw_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_llama31_8B_raw_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['RAW llama31_8B'],
    'Jaccard':      [f"{overall_means['ji_raw_llama31_8B']:.2f}±{overall_stds['ji_raw_llama31_8B']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['similarity_score_medcpt_dot_raw_llama31_8B']:.2f}±{overall_stds['similarity_score_medcpt_dot_raw_llama31_8B']:.2f}"],
    'Scincl (cos)': [f"{overall_means['similarity_score_scincl_cosine_raw_llama31_8B']:.2f}±{overall_stds['similarity_score_scincl_cosine_raw_llama31_8B']:.2f}"],
    'Correctness':  [f"{overall_means['score_raw_llama31_8B']:.2f}±{overall_stds['score_raw_llama31_8B']:.2f}"]
})

summary

        Condition    Jaccard MedCPT (cos) Scincl (cos) Correctness
0  RAW llama31_8B  0.07±0.03   60.57±2.93    0.87±0.05   2.13±0.78

# 3. Phi 4

## 3.1. Phi4 FL:

In [136]:
df_phi4_fl_exp = pd.read_pickle('july_result/phi4_FL_318_metrics.pkl')
df_phi4_fl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'iteration_results', 'respond_llm',
       'respond_time_llm', 'evaluation_time_llm',
       'total_evaluation_time_per_row', 'prompts_per_iteration',
       'pmid_contexts_per_iteration', 'pmid_changes_per_iteration',
       'termination_reason', 'iterations_completed', 'final_explanation',
       'pmid_text', 'ji_fl_phi4', 'phi4_fl_similarity_score_medcpt_dot',
       'phi4_fl_similarity_score_scincl_dot', 'score_fl_phi4',
       'feedback_bseline'],
      dtype='object')

In [274]:
cols = [
    'ji_fl_phi4',
    'phi4_fl_similarity_score_medcpt_dot',
    'phi4_fl_similarity_score_scincl_dot',
    'score_fl_phi4'
]

grouped_df = df_phi4_fl_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_phi4_fl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['Feedback Loop (FL) Phi4'],
    'Jaccard':      [f"{overall_means['ji_fl_phi4']:.2f}±{overall_stds['ji_fl_phi4']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['phi4_fl_similarity_score_medcpt_dot']:.2f}±{overall_stds['phi4_fl_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['phi4_fl_similarity_score_scincl_dot']:.2f}±{overall_stds['phi4_fl_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['score_fl_phi4']:.2f}±{overall_stds['score_fl_phi4']:.2f}"]
})

summary

                 Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  Feedback Loop (FL) Phi4  0.08±0.03   61.98±3.37  496.04±28.58   2.52±1.13

## 3.2. Phi4 BL:

In [110]:
df_phi4_bl_exp = pd.read_pickle('july_result/phi4_BL_318_metrics.pkl')
df_phi4_bl_exp.columns

Index(['pair', 'index', 'path', 'score', 'context_pmids', 'pmid', 'subj_name',
       'obj_name', 'top_3_labels', 'sorted_context_pmids',
       'final_context_pmids', 'basedLine_response_phi4', 'bl_prompt_context',
       'pmid_text', 'ji_baseline_phi4',
       'baseline_similarity_score_medcpt_dot_phi4',
       'baseline_similarity_score_scincl_dot_phi4', 'score_bseline_phi4',
       'feedback_bseline', 'evaluate_llm_response', 'all_predicates',
       'bad_predicates', 'good_predicates', 'agatha_score', 'num_predicates',
       'number_bad_predicates'],
      dtype='object')

In [275]:
cols = [
    'ji_baseline_phi4',
    'baseline_similarity_score_medcpt_dot_phi4',
    'baseline_similarity_score_scincl_dot_phi4',
    'score_bseline_phi4'
]

grouped_df = df_phi4_bl_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_phi4_bl_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['(BL) Phi4'],
    'Jaccard':      [f"{overall_means['ji_baseline_phi4']:.2f}±{overall_stds['ji_baseline_phi4']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['baseline_similarity_score_medcpt_dot_phi4']:.2f}±{overall_stds['baseline_similarity_score_medcpt_dot_phi4']:.2f}"],
    'Scincl (cos)': [f"{overall_means['baseline_similarity_score_scincl_dot_phi4']:.2f}±{overall_stds['baseline_similarity_score_scincl_dot_phi4']:.2f}"],
    'Correctness':  [f"{overall_means['score_bseline_phi4']:.2f}±{overall_stds['score_bseline_phi4']:.2f}"]
})

summary

   Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  (BL) Phi4  0.08±0.03   62.05±3.40  497.18±27.51   2.42±1.06

## 3.3. Phi4 RAW:

In [94]:
df_phi4_raw_exp = pd.read_pickle('july_result/phi4_RAW_318_metrics.pkl')
df_phi4_raw_exp.columns

Index(['subj_name', 'obj_name', 'index', 'Raw_Phi4_response',
       'raw_phi4_similarity_score_medcpt_dot',
       'raw_phi4_similarity_score_scincl_dot', 'raw_score_phi4',
       'raw_feedback_phi4', 'raw_phi4_ji'],
      dtype='object')

In [279]:
cols = [
    'raw_phi4_ji',
    'raw_phi4_similarity_score_medcpt_dot',
    'raw_phi4_similarity_score_scincl_dot',
    'raw_score_phi4'
]

grouped_df = df_phi4_raw_exp.groupby('index').agg('mean', numeric_only=True)
overall_means = grouped_df[cols].mean()
summary_df = overall_means.to_frame().T

grp = df_phi4_raw_exp.groupby('index')[cols]
mean_per_index = grp.mean()
std_per_index  = grp.std(ddof=1)

overall_means = mean_per_index.mean()
overall_stds  = std_per_index.mean()

summary = pd.DataFrame({
    'Condition':    ['(RAW) Phi4'],
    'Jaccard':      [f"{overall_means['raw_phi4_ji']:.2f}±{overall_stds['raw_phi4_ji']:.2f}"],
    'MedCPT (cos)': [f"{overall_means['raw_phi4_similarity_score_medcpt_dot']:.2f}±{overall_stds['raw_phi4_similarity_score_medcpt_dot']:.2f}"],
    'Scincl (cos)': [f"{overall_means['raw_phi4_similarity_score_scincl_dot']:.2f}±{overall_stds['raw_phi4_similarity_score_scincl_dot']:.2f}"],
    'Correctness':  [f"{overall_means['raw_score_phi4']:.2f}±{overall_stds['raw_score_phi4']:.2f}"]
})

summary

    Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  (RAW) Phi4  0.07±0.03   61.10±2.95  488.00±27.44   2.46±0.83

In [280]:
# from IPython.display import display
# display(summary_df, summary)

,raw_phi4_ji,raw_phi4_similarity_score_medcpt_dot,raw_phi4_similarity_score_scincl_dot,raw_score_phi4
0,0.069556,61.098408,488.002289,2.462264

    Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0  (RAW) Phi4  0.07±0.03   61.10±2.95  488.00±27.44   2.46±0.83

In [77]:
!pwd

/work/acslab/users/svalipou/Year_2025_Experiments/Expalianability_Paper_Exp/1_JULY_full_df_july_13

In [288]:
import pandas as pd

def summarize_df(df, cols, label):
    grp = df.groupby('index')[cols]
    mean_idx = grp.mean()
    std_idx  = grp.std(ddof=1)
    overall_mean = mean_idx.mean()
    overall_std  = std_idx.mean()
    return pd.DataFrame([{
        'Condition':    label,
        'Jaccard':      f"{overall_mean[cols[0]]:.2f}±{overall_std[cols[0]]:.2f}",
        'MedCPT (cos)': f"{overall_mean[cols[1]]:.2f}±{overall_std[cols[1]]:.2f}",
        'Scincl (cos)': f"{overall_mean[cols[2]]:.2f}±{overall_std[cols[2]]:.2f}",
        'Correctness':  f"{overall_mean[cols[3]]:.2f}±{overall_std[cols[3]]:.2f}"
    }])

experiments = [
    (df_phi4_raw_exp,
     ['raw_phi4_ji', 'raw_phi4_similarity_score_medcpt_dot',
      'raw_phi4_similarity_score_scincl_dot', 'raw_score_phi4'],
     '(RAW) Phi-4'),
    (df_phi4_bl_exp,
     ['ji_baseline_phi4', 'baseline_similarity_score_medcpt_dot_phi4',
      'baseline_similarity_score_scincl_dot_phi4', 'score_bseline_phi4'],
     '(BL) Phi-4'),
    (df_phi4_fl_exp,
     ['ji_fl_phi4', 'phi4_fl_similarity_score_medcpt_dot',
      'phi4_fl_similarity_score_scincl_dot', 'score_fl_phi4'],
     '(FL) Phi-4'),

    (df_llama31_8B_raw_exp,
     ['ji_raw_llama31_8B', 'similarity_score_medcpt_dot_raw_llama31_8B',
      'similarity_score_scincl_dot_raw_llama31_8B', 'score_raw_llama31_8B'],
     '(RAW) Llama-3.1 8B'),
    (df_llama31_8B_bl_exp,
     ['llama31_8B_ji_bl', 'llama31_8B_bl_similarity_score_medcpt_dot',
      'llama31_8B_bl_similarity_score_scincl_dot', 'llama31_8B_score_bseline'],
     '(BL) Llama-3.1 8B'),
    (df_llama31_8B_fl_exp,
     ['llama31_8B_ji_fl', 'llama31_8B_fl_similarity_score_medcpt_dot',
      'llama31_8B_fl_similarity_score_scincl_dot', 'llama31_8B_score_fl'],
     '(FL) Llama-3.1 8B'),

    (df_llama33_70B_raw_exp,
     ['ji_raw_llama33_70B', 'similarity_score_medcpt_dot_raw_llama33_70B',
      'similarity_score_scincl_dot_raw_llama33_70B', 'score_raw_llama33_70B'],
     '(RAW) Llama-3.3 70B'),
    (df_llama33_70B_bl_exp,
     ['llama33_70B_ji_bl', 'llama33_70B_bl_bl_similarity_score_medcpt_dot',
      'llama33_70B_bl_similarity_score_scincl_dot', 'llama33_70B_score_bl'],
     '(BL) Llama-3.3 70B'),
    (df_llama33_70B_fl_exp,
     ['llama33_70B_ji_fl', 'llama33_70B_fl_similarity_score_medcpt_dot',
      'llama33_70B_fl_similarity_score_scincl_dot', 'llama33_70B_fl_score'],
     '(FL) Llama-3.3 70B'),
]

# Compute and concatenate all summaries
summaries = [summarize_df(df, cols, label) for df, cols, label in experiments]
all_summary = pd.concat(summaries, ignore_index=True)
all_summary

             Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0          (RAW) Phi-4  0.07±0.03   61.10±2.95  488.00±27.44   2.46±0.83
1           (BL) Phi-4  0.08±0.03   62.05±3.40  497.18±27.51   2.42±1.06
2           (FL) Phi-4  0.08±0.03   61.98±3.37  496.04±28.58   2.52±1.13
3   (RAW) Llama-3.1 8B  0.07±0.03   60.57±2.93  488.67±29.69   2.13±0.78
4    (BL) Llama-3.1 8B  0.07±0.03   61.51±3.25  494.37±26.09   1.84±0.90
5    (FL) Llama-3.1 8B  0.07±0.03   61.17±3.24  491.25±26.50   1.75±0.86
6  (RAW) Llama-3.3 70B  0.07±0.03   60.71±2.84  490.79±28.03   2.53±0.84
7   (BL) Llama-3.3 70B  0.08±0.03   61.86±3.29  495.75±27.16   2.15±1.01
8   (FL) Llama-3.3 70B  0.08±0.03   61.82±3.28  495.28±26.54   2.36±1.05

## 4. Adding VAIV:

In [295]:
vaiv_1st_df = pd.read_pickle('./VAIV_RES/vaiv_1st_metrics.pkl')
vaiv_2nd_df = pd.read_pickle('./VAIV_RES/vaiv_2nd_metrics.pkl')
vaiv_3rd_df = pd.read_pickle('./VAIV_RES/vaiv_3rd_metrics.pkl')

selected_columns = ["jaccard_sim", "similarity_score_medcpt_dot", "similarity_score_scincl_dot", "score"]

mean_1 = vaiv_1st_df[selected_columns].mean()
mean_2 = vaiv_2nd_df[selected_columns].mean()
mean_3 = vaiv_3rd_df[selected_columns].mean()


vaiv_df = pd.DataFrame([mean_1, mean_2, mean_3])
vaiv_mean = vaiv_df.mean()
vaiv_std = vaiv_df.std(ddof=1)

vaiv_row = pd.DataFrame([{
    'Condition':    '(VAIV) ChatGPT-3.5',
    'Jaccard':      f"{vaiv_mean['jaccard_sim']:.2f}±{vaiv_std['jaccard_sim']:.2f}",
    'MedCPT (cos)': f"{vaiv_mean['similarity_score_medcpt_dot']:.2f}±{vaiv_std['similarity_score_medcpt_dot']:.2f}",
    'Scincl (cos)': f"{vaiv_mean['similarity_score_scincl_dot']:.2f}±{vaiv_std['similarity_score_scincl_dot']:.2f}",
    'Correctness':  f"{vaiv_mean['score']:.2f}±{vaiv_std['score']:.2f}"
}])


all_summary_with_vaiv = pd.concat([all_summary, vaiv_row], ignore_index=True)
all_summary_with_vaiv

             Condition    Jaccard MedCPT (cos)  Scincl (cos) Correctness
0          (RAW) Phi-4  0.07±0.03   61.10±2.95  488.00±27.44   2.46±0.83
1           (BL) Phi-4  0.08±0.03   62.05±3.40  497.18±27.51   2.42±1.06
2           (FL) Phi-4  0.08±0.03   61.98±3.37  496.04±28.58   2.52±1.13
3   (RAW) Llama-3.1 8B  0.07±0.03   60.57±2.93  488.67±29.69   2.13±0.78
4    (BL) Llama-3.1 8B  0.07±0.03   61.51±3.25  494.37±26.09   1.84±0.90
5    (FL) Llama-3.1 8B  0.07±0.03   61.17±3.24  491.25±26.50   1.75±0.86
6  (RAW) Llama-3.3 70B  0.07±0.03   60.71±2.84  490.79±28.03   2.53±0.84
7   (BL) Llama-3.3 70B  0.08±0.03   61.86±3.29  495.75±27.16   2.15±1.01
8   (FL) Llama-3.3 70B  0.08±0.03   61.82±3.28  495.28±26.54   2.36±1.05
9   (VAIV) ChatGPT-3.5  0.06±0.00   60.90±0.11   480.93±1.28   1.63±0.05

In [294]:
import pandas as pd

experiments = [
    ("./july_result/phi4_RAW_318_metrics.pkl",
     ['raw_phi4_ji', 'raw_phi4_similarity_score_medcpt_dot',
      'raw_phi4_similarity_score_scincl_dot', 'raw_score_phi4'],
     '(RAW) Phi-4'),
    ("./july_result/phi4_BL_318_metrics.pkl",
     ['ji_baseline_phi4', 'baseline_similarity_score_medcpt_dot_phi4',
      'baseline_similarity_score_scincl_dot_phi4', 'score_bseline_phi4'],
     '(BL) Phi-4'),
    ("./july_result/phi4_FL_318_metrics.pkl",
     ['ji_fl_phi4', 'phi4_fl_similarity_score_medcpt_dot',
      'phi4_fl_similarity_score_scincl_dot', 'score_fl_phi4'],
     '(FL) Phi-4'),
    ("./july_result/llama31_8B_RAW_318_metrics.pkl",
     ['ji_raw_llama31_8B', 'similarity_score_medcpt_dot_raw_llama31_8B',
      'similarity_score_scincl_dot_raw_llama31_8B', 'score_raw_llama31_8B'],
     '(RAW) Llama-3.1 8B'),
    ("./july_result/llama31_8B_BL_318_metrics.pkl",
     ['llama31_8B_ji_bl', 'llama31_8B_bl_similarity_score_medcpt_dot',
      'llama31_8B_bl_similarity_score_scincl_dot', 'llama31_8B_score_bseline'],
     '(BL) Llama-3.1 8B'),
    ("./july_result/llama31_8B_FL_318_metrics.pkl",
     ['llama31_8B_ji_fl', 'llama31_8B_fl_similarity_score_medcpt_dot',
      'llama31_8B_fl_similarity_score_scincl_dot', 'llama31_8B_score_fl'],
     '(FL) Llama-3.1 8B'),
    ("./july_result/llama33_70B_RAW_318_metrics.pkl",
     ['ji_raw_llama33_70B', 'similarity_score_medcpt_dot_raw_llama33_70B',
      'similarity_score_scincl_dot_raw_llama33_70B', 'score_raw_llama33_70B'],
     '(RAW) Llama-3.3 70B'),
    ("./july_result/llama33_70B_BL_318_metrics.pkl",
     ['llama33_70B_ji_bl', 'llama33_70B_bl_bl_similarity_score_medcpt_dot',
      'llama33_70B_bl_similarity_score_scincl_dot', 'llama33_70B_score_bl'],
     '(BL) Llama-3.3 70B'),
    ("./july_result/llama33_70B_FL_318_metrics.pkl",
     ['llama33_70B_ji_fl', 'llama33_70B_fl_similarity_score_medcpt_dot',
      'llama33_70B_fl_similarity_score_scincl_dot', 'llama33_70B_fl_score'],
     '(FL) Llama-3.3 70B'),
]

rows = []
for path, cols, cond in experiments:
    df = pd.read_pickle(path)
    overall = df.groupby('index')[cols].mean().mean()
    rows.append({
        'Condition':     cond,
        'Jaccard Index': overall[cols[0]],
        'MedCPT (·)':    overall[cols[1]],
        'Scincl (·)':    overall[cols[2]],
        'Correctness':   overall[cols[3]]
    })

summary_df = pd.DataFrame(rows).round(3)
summary_df

             Condition  Jaccard Index  MedCPT (·)  Scincl (·)  Correctness
0          (RAW) Phi-4          0.070      61.098     488.002        2.462
1           (BL) Phi-4          0.085      62.052     497.184        2.415
2           (FL) Phi-4          0.080      61.982     496.042        2.519
3   (RAW) Llama-3.1 8B          0.067      60.573     488.665        2.129
4    (BL) Llama-3.1 8B          0.075      61.514     494.373        1.840
5    (FL) Llama-3.1 8B          0.073      61.169     491.247        1.745
6  (RAW) Llama-3.3 70B          0.071      60.711     490.788        2.525
7   (BL) Llama-3.3 70B          0.081      61.859     495.750        2.151
8   (FL) Llama-3.3 70B          0.078      61.815     495.283        2.358

In [296]:
experiments = [
    ("./july_result/phi4_RAW_318_metrics.pkl",
     ['raw_phi4_ji', 'raw_phi4_similarity_score_medcpt_dot',
      'raw_phi4_similarity_score_scincl_dot', 'raw_score_phi4'],
     '(RAW) Phi-4'),
    ("./july_result/phi4_BL_318_metrics.pkl",
     ['ji_baseline_phi4', 'baseline_similarity_score_medcpt_dot_phi4',
      'baseline_similarity_score_scincl_dot_phi4', 'score_bseline_phi4'],
     '(BL) Phi-4'),
    ("./july_result/phi4_FL_318_metrics.pkl",
     ['ji_fl_phi4', 'phi4_fl_similarity_score_medcpt_dot',
      'phi4_fl_similarity_score_scincl_dot', 'score_fl_phi4'],
     '(FL) Phi-4'),
    ("./july_result/llama31_8B_RAW_318_metrics.pkl",
     ['ji_raw_llama31_8B', 'similarity_score_medcpt_dot_raw_llama31_8B',
      'similarity_score_scincl_dot_raw_llama31_8B', 'score_raw_llama31_8B'],
     '(RAW) Llama-3.1 8B'),
    ("./july_result/llama31_8B_BL_318_metrics.pkl",
     ['llama31_8B_ji_bl', 'llama31_8B_bl_similarity_score_medcpt_dot',
      'llama31_8B_bl_similarity_score_scincl_dot', 'llama31_8B_score_bseline'],
     '(BL) Llama-3.1 8B'),
    ("./july_result/llama31_8B_FL_318_metrics.pkl",
     ['llama31_8B_ji_fl', 'llama31_8B_fl_similarity_score_medcpt_dot',
      'llama31_8B_fl_similarity_score_scincl_dot', 'llama31_8B_score_fl'],
     '(FL) Llama-3.1 8B'),
    ("./july_result/llama33_70B_RAW_318_metrics.pkl",
     ['ji_raw_llama33_70B', 'similarity_score_medcpt_dot_raw_llama33_70B',
      'similarity_score_scincl_dot_raw_llama33_70B', 'score_raw_llama33_70B'],
     '(RAW) Llama-3.3 70B'),
    ("./july_result/llama33_70B_BL_318_metrics.pkl",
     ['llama33_70B_ji_bl', 'llama33_70B_bl_bl_similarity_score_medcpt_dot',
      'llama33_70B_bl_similarity_score_scincl_dot', 'llama33_70B_score_bl'],
     '(BL) Llama-3.3 70B'),
    ("./july_result/llama33_70B_FL_318_metrics.pkl",
     ['llama33_70B_ji_fl', 'llama33_70B_fl_similarity_score_medcpt_dot',
      'llama33_70B_fl_similarity_score_scincl_dot', 'llama33_70B_fl_score'],
     '(FL) Llama-3.3 70B'),
]

rows = []
for path, cols, cond in experiments:
    df = pd.read_pickle(path)
    overall = df.groupby('index')[cols].mean().mean()
    rows.append({
        'Condition':     cond,
        'Jaccard Index': overall[cols[0]],
        'MedCPT (·)':    overall[cols[1]],
        'Scincl (·)':    overall[cols[2]],
        'Correctness':   overall[cols[3]]
    })

summary_df = pd.DataFrame(rows).round(3)
vaiv_1 = pd.read_pickle('./VAIV_RES/vaiv_1st_metrics.pkl')
vaiv_2 = pd.read_pickle('./VAIV_RES/vaiv_2nd_metrics.pkl')
vaiv_3 = pd.read_pickle('./VAIV_RES/vaiv_3rd_metrics.pkl')

cols_vaiv = ["jaccard_sim", "similarity_score_medcpt_dot", "similarity_score_scincl_dot", "score"]
vaiv_mean = pd.DataFrame([
    vaiv_1[cols_vaiv].mean(),
    vaiv_2[cols_vaiv].mean(),
    vaiv_3[cols_vaiv].mean()
]).mean()

summary_df.loc[len(summary_df)] = {
    'Condition': '(VAIV) ChatGPT-3.5',
    'Jaccard Index': round(vaiv_mean['jaccard_sim'], 3),
    'MedCPT (·)':    round(vaiv_mean['similarity_score_medcpt_dot'], 3),
    'Scincl (·)':    round(vaiv_mean['similarity_score_scincl_dot'], 3),
    'Correctness':   round(vaiv_mean['score'], 3),
}
summary_df

             Condition  Jaccard Index  MedCPT (·)  Scincl (·)  Correctness
0          (RAW) Phi-4          0.070      61.098     488.002        2.462
1           (BL) Phi-4          0.085      62.052     497.184        2.415
2           (FL) Phi-4          0.080      61.982     496.042        2.519
3   (RAW) Llama-3.1 8B          0.067      60.573     488.665        2.129
4    (BL) Llama-3.1 8B          0.075      61.514     494.373        1.840
5    (FL) Llama-3.1 8B          0.073      61.169     491.247        1.745
6  (RAW) Llama-3.3 70B          0.071      60.711     490.788        2.525
7   (BL) Llama-3.3 70B          0.081      61.859     495.750        2.151
8   (FL) Llama-3.3 70B          0.078      61.815     495.283        2.358
9   (VAIV) ChatGPT-3.5          0.065      60.904     480.932        1.629